### PR TITLE
Fix/56/lodash merge sec vulnerability

### LINKED ISSUE #56: High severity vulnerability
Please update lodash merge to resolve a high severity vulnerability.

```console
$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash.merge                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.6.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ hbs-cli                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ hbs-cli > lodash.merge                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1066                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash.merge                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.6.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ hbs-cli                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ hbs-cli > lodash.merge                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1067                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 2 high severity vulnerabilities in 1730 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
```

### PR DESCRIPTION
**Pull request by scottyeck**
Resolves https://github.com/keithamus/hbs-cli/issues/56, plus adds a lockfile.

### CODE REVIEW

**Review by keithamus — APPROVED** [review]

**Comment by keithamus** [comment]
Thanks @scottyeck!

**Comment by juanheyns** [comment]
@keithamus any chance you can create a release with this change in, 1.4.1 perhaps?

**Comment by keithamus** [comment]
Released :+1:

**Comment by juanheyns** [comment]
Thanks

**Pull request merged**
